invoice_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import hello_world_view
# http://127.0.0.1:8000

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', hello_world_view),
    path('', include('invoices.urls', namespace='invoices'))
]

# http://127.0.0.1:8000/media/img.jpg
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Invoice admin system'
admin.site.index_title = 'Management'

invoices/urls.py
from django.urls import path
from .views import InvoiceListView, InvoiceFormView, SimpleTemplateView, InvoiceUpdateView, AddPositionsFormView, CloseInvoiceView, InvoicePositionDeleteView

app_name = "invoices"

urlpatterns = [
    path('', InvoiceListView.as_view(), name="main"),
    path('new/', InvoiceFormView.as_view(), name="create"),
    # path('<pk>/', SimpleTemplateView.as_view(), name='simple_template'),
    path('<pk>/', AddPositionsFormView.as_view(), name='detail'),
    path('<pk>/close/', CloseInvoiceView.as_view(), name='close'),
    path('<pk>/update/', InvoiceUpdateView.as_view(), name='update'),
    path('<pk>/delete/<int:position_pk>', InvoicePositionDeleteView.as_view(), name='position-delete')
]

invoices/models.py
from django.db import models
from profiles.models import Profile
from receivers.models import Receiver
# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Invoice(models.Model):
    # referencing the tables that we already created.
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE)
    # invoice number
    number = models.CharField(max_length=150)
    completion_date = models.DateField()
    issue_date = models.DateField()
    payment_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    # if closed - hide add positions and unable adding new ones
    closed = models.BooleanField(default=False)
    # for educational purposes not so req for this project
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f"Invoice number: {self.number}, pk: {self.pk}"

    # def get_tags(self):
    #     return self.tags.all()

    @property
    def tags(self):
        return self.tags.all()

    @property
    def positions(self):
        return self.position_set.all()

    @property
    def total_amount(self):
        total = 0
        qs = self.positions
        for pos in qs:
            total += pos.amount
        return total

invoices/forms.py
from django import forms
from .models import Invoice
from django.core.exceptions import ValidationError


class InvoiceForm(forms.ModelForm):
    completion_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    issue_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    payment_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Invoice
        fields = ('receiver', 'number', 'completion_date',
                  'issue_date', 'payment_date')

        # labels = {
        #     'receiver': 'test1',
        #     'number': 'test2',
        #     'completion_date': 'test3',

        # }

    def clean_number(self):
        number = self.cleaned_data.get('number')
        if len(number) < 10:
            raise ValidationError("Number is too short.")
        return number

invoices/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from cProfile import Profile
from profiles.models import Profile
from django.views.generic import (
    ListView, FormView, TemplateView, DetailView, UpdateView, RedirectView, DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


from .forms import InvoiceForm
from positions.models import Position
from positions.forms import PositionForm
from .models import Invoice
from .mixins import InvoiceNotClosed
# Create your views here.


class InvoiceListView(LoginRequiredMixin, ListView):
    model = Invoice
    # invoice_list.html -> this is the default html so we are changing it below
    template_name = "invoices/main.html"
    paginate_by = 2
    context_object_name = "qs"

    # Invoice.objects.all() -> default queryset

    def get_queryset(self):
        # profile = Profile.objects.get(user=self.request.user)
        # qs = Invoice.objects.filter(profile=profile).order_by('-created')
        # return qs
        # instead of above we can use
        profile = get_object_or_404(Profile, user=self.request.user)
        return super().get_queryset().filter(profile=profile).order_by('-created')


class InvoiceFormView(LoginRequiredMixin, FormView):
    form_class = InvoiceForm
    template_name = 'invoices/create.html'
    # success_url = reverse_lazy('invoices:main')
    i_instance = None

    def get_success_url(self):
        return reverse('invoices:detail', kwargs={'pk': self.i_instance.pk})

    def form_valid(self, form):
        # logic here
        profile = Profile.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        return super().form_valid(form)


class SimpleTemplateView(LoginRequiredMixin, DetailView):
    model = Invoice
    template_name = 'invoices/detail.html'


# class SimpleTemplateView(TemplateView):
#     template_name = 'invoices/simple_template.html'

class AddPositionsFormView(LoginRequiredMixin, FormView):
    form_class = PositionForm
    template_name = 'invoices/detail.html'

    def get_success_url(self):
        return self.request.path

    def form_valid(self, form):
        invoice_pk = self.kwargs.get('pk')
        invoice_obj = Invoice.objects.get(pk=invoice_pk)
        instance = form.save(commit=False)
        instance.invoice = invoice_obj
        form.save()
        messages.info(
            self.request, f'Successfully added position - {instance.title}')

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice_obj = Invoice.objects.get(pk=self.kwargs.get('pk'))
        qs = invoice_obj.positions
        context['obj'] = invoice_obj
        context['qs'] = qs

        return context


class InvoiceUpdateView(LoginRequiredMixin, InvoiceNotClosed, UpdateView):
    model = Invoice
    template_name = 'invoices/update.html'
    form_class = InvoiceForm
    success_url = reverse_lazy('invoices:main')

    def form_valid(self, form):
        instance = form.save()
        messages.info(
            self.request, f'Successfully updated invoice - {instance.number}')
        return super().form_valid(form)


class CloseInvoiceView(LoginRequiredMixin, RedirectView):
    pattern_name = 'invoices:detail'

    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Invoice.objects.get(pk=pk)
        obj.closed = True
        obj.save()
        return super().get_redirect_url(*args, **kwargs)


class InvoicePositionDeleteView(LoginRequiredMixin, InvoiceNotClosed, DeleteView):
    model = Position
    template_name = 'invoices/position_confirm_delete.html'

    # /<pk>/delete/<position_pk>
    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Position.objects.get(pk=pk)
        return obj

    def get_success_url(self):
        messages.info(self.request, f'Deleted Position - {self.object.title}')
        return reverse('invoices:detail', kwargs={'pk': self.object.invoice.id})


# from django.http import HttpResponse
# from django.template.loader import get_template
# from xhtml2pdf import pisa
# from django.contrib.staticfiles import finders

# @login_required
# def invoice_pdf_view(request, **kwargs):
#     pk = kwargs.get('pk')
#     obj = Invoice.objects.get(pk=pk)

#     logo_result = finders.find('img/logo.png')
#     font_result = finders.find('fonts/Lato-Regular.ttf')
    
#     #show search location results
#     searched_locations = finders.searched_locations
#     print(searched_locations)

invoices/templates/invoices/create.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block title %}
Create
{% endblock title %} 
{% block content %}
<form method="POST" action="">
	{% csrf_token %} 
    {{ form|crispy }}
	<button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}

invoices/templates/invoices/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Detail Page{% endblock title %}

{% block content %}


  <!--add Positions Modal -->
  <div class="modal fade" id="addPositionsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Positions</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="" method="POST">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-primary mt-3">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>

    <!--close invoice Modal -->
    <div class="modal fade" id="closeInvoiceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure you want to close the invoice?
            </div>
            <div class="modal-footer">
              <a href="{% url 'invoices:close' obj.pk %}" class="btn btn-secondary">Close</a>
            </div>
          </div>
        </div>
      </div>

  <div>
    {% if not obj.closed %}
            <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPositionsModal">
        + Add Positions
    </button>
    <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#closeInvoiceModal">
        Close
    </button>
    {% else %}
        <a href="#" class="btn btn-danger">pdf</a>
    {% endif %}

  
  </div>
  

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-primary mt-2"> 
                    {{message}}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div class="mt-3">
        <h5>Receiver: {{obj.receiver.name}}</h5>
        <hr>
        <h3>Positions</h3>

        {% if qs %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>
            <tbody>
                {% for item in qs %}
                <tr style="vertical-align:middle;">
                    <th scope="row">{{forloop.counter}}</th>
                    <td> {{item.title}} </td>
                    <td> {{item.description}} </td>
                    <td> {{item.amount}}$ </td>
                    <td>
                            {% if not obj.closed %}
                                <a href="{% url 'invoices:position-delete' obj.pk item.pk%}" class="btn btn-danger">x</a>
                                {% else %}
                                closed
                            {% endif %}
                        </td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>

          <div class="mt-2 text-end">
            <h2>Total Amount: ${{obj.total_amount}}</h2>
          </div>
        {% else %} <h5>No Positions added......</h5>{% endif %}
    </div>
{% endblock content %}

invoices/templates/invoices/main.html
{%extends "base.html"%}
{% block title %}home{% endblock title %}
{% block content %}
{% if messages %}{% for message in messages %}{% if message.tags == 'info' %}
<div class="alert alert-primary mt-2"> {{message}} </div>
{% endif %}{% endfor %}{% endif %}
{% comment %} {% for obj in object_list %}<b>{{obj.number}}</b></br>{% endfor %} {% endcomment %}
{% if qs %}
    {% for obj in qs %}
    <div class="card mb-2" style="width:100%">
        <div class="card-body">
            <h5 class="card-title">{{obj.number}} - {{obj.receiver.name}}</h5>
            <div class="card-text">Completion Date: {{obj.completion_date}} </div>
            <div class="text-muted">Amount: {{obj.total_amount}} $</div>
            <div class="mt-2">
                <a href="{% url 'invoices:detail' obj.pk%}" class="btn btn-primary">Details</a>
                {% if not obj.closed %}
                  <a href="{% url 'invoices:update' obj.pk%}" class="btn btn-info">Update</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
<h3>No invoices created.....</h3>
{% endif %}

{% if is_paginated %}
<nav aria-label="invoice pagination">
    <ul class="pagination">
      <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
        <a 
        {% if page_obj.has_previous %}href="?page={{page_obj.previous_page_number}}"{% endif %} class="page-link" tabindex="-1"
        >Previous</a>
      </li>
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
      {% endfor %}
     
      <li class="page-item {% if page_obj.has_next %} {% else %} disabled {% endif %}">
        <a 
        {% if page_obj.has_next %}href="?page={{page_obj.next_page_number}}"{% endif %} 
        class="page-link" >Next</a>
      </li>
    </ul>
  </nav>
{% endif %}

{% endblock content %}

invoices/templates/invoices/position_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete position{% endblock title %}

{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete <b>"{{object.title}}"</b> ?</p>
        <button type="submit" class="btn btn-primary">
            Yes
        </button>
    </form>
{% endblock content %}

invoices/templates/invoices/simple_template.html
{% extends 'base.html' %}
{% block title %}hello{% endblock title %}
{% block content %} {{object.pk}} - {{object.number}} {% endblock content %}

invoices/templates/invoices/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form | crispy}}
        <button type = "submit" class="btn btn-primary mt-2">
            Update
        </button> 
    </form>
{% endblock content %}